---
title: "Relating Lindley's Paradox to the Exposure of Model Assumptions as a Catalyst for Implementation Science"
output: html_document
author: Scott H. Harrison, PhD
date: April 27, 2021
---

# Summary

<!--- Indicate question (one or two sentences on purpose) --->
Overlooked options for effective treatment may stem from lack of access and transparency regarding reproducible data analyses, reducing incorporation of viable treatments into standard medical practice. Some of this challenge may be critically addressed by further exposing underlying model assumptions in a data analysis to more explicitly take into account both the degree by which truly effective treatments are potentially discounted, and also the degree by which ineffective treatments are potentially evaluated as being effective.
<!--- Indicate basic experimental design and methods (a few sentences) --->
In this study, we present a reproducible evaluation for how treatment data can be alternatively analyzed via frequentist versus Bayesian perspectives. 
<!--- Primary findings (some exemplifying detail and quantitative report is recommended; several sentences) --->
The contrasting outcomes in analysis across these perspectives relates to Lindley's paradox.
<!--- Interpretation (what can be discussed or concluded; what are the implications) --->
We discuss how Lindley's paradox may reveal an essential consideration regarding analysis of public health data as concerns implementation science.

# Methods

<!--- Be sure to describe software, computational and mathematical models as are applicable to your study. --->

Example of mathematical equation rendering:

$${a}=\frac{b^c}{x_i+y_j}.$$

# Results

## Please use subsection headings like this.

<!--- Results should provide both an adequate level of detail and summary of direct findings. --->.

# Discussion

<!--- Discussion may be optionally retitled as Discussion and Conclusion --->

<!--- Interpret results in terms of what was expected and what was found. Be coherent with rest of manuscript. If there is an introduction section, how does this work build on those themes expounded upon in the introduction? Summarize the contributions of this work. You can also consider indicating new questions and future direction. --->

# Supplemental

```{r supplemental}
sessionInfo()
```
